Entities/Custom.cs
using System;

namespace Presentacion.Entities;

public class Custom
{
    public int CustomId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime BorsDay { get; set; }

}

Entities/Proveedor.cs
using System;

namespace Presentacion.Entities;

public class Proveedor
{
    public int ProveedorId { get; set; }
    public string FirstName { get; set; }   
    public string LastName { get; set; }
    public DateTime BornDate { get; set; }
}

Controllers/CustomController.cs
using Microsoft.AspNetCore.Mvc;
using Presentacion.Interfaces;

namespace Presentacion.Controllers
{
    public class CustomController : Controller
    {
        private readonly ICustomRepository customRepository;

        public CustomController(ICustomRepository customRepository)
        {
            this.customRepository = customRepository;
        }

        // GET: CustomController
        [ResponseCache(Duration = 60, Location = ResponseCacheLocation.Any, NoStore = true)]
        public ActionResult Index()
        {
            return View();
        }

        

    }
}

Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Presentacion.Interfaces;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICustomRepository customRepository;

        public HomeController(ICustomRepository customRepository)
        {
            this.customRepository = customRepository;
        }

        public async Task<IActionResult> Index()
        {
            var custom = await customRepository.CustomList();
            return View(custom);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Mvc;
using Presentacion.Interfaces;

namespace Presentacion.Controllers
{
    public class ProveedorController : Controller
    {
        private readonly IProveedorRepository proveedorRepository;

        public ProveedorController(IProveedorRepository proveedorRepository)
        {
            this.proveedorRepository = proveedorRepository;
        }
        // GET: ProveedorController
        public ActionResult Index()
        {
            var proveedores = proveedorRepository.GetAllProveedores();
            return View(proveedores);
        }

    }
}

Views/Custom/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <h1 class="display-4">Custom Index</h1>
</div>
<p class="alert alert-danger">@DateTime.Now.ToLongTimeString()</p>

Views/Home/Index.cshtml
@model List<CustomView>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>



<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Birthday</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var custom in Model)
            {
                <tr>
                    <td>@custom.CustomId</td>
                    <td>@custom.FirstName</td>
                    <td>@custom.LastName</td>
                    <td>@custom.BorsDay</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Proveedor/Index.cshtml
@model List<Presentacion.ModelViews.ProveedorView>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Proveedor List</h1>
</div>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>ProveedorId</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Born Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var proveedor in Model)
            {
                <tr>
                    <td>@proveedor.ProveedorId</td>
                    <td>@proveedor.FirstName</td>
                    <td>@proveedor.LastName</td>
                    <td>@proveedor.BornDate.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentacion.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentacion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Custom"
                                asp-action="Index">Custom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor"
                                asp-action="Index">Proveedor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Presentacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>